---
title: "Univariate relationships in IN Ponds data"
geometry: margin=2.54cm
output: pdf_document
header-includes: \usepackage{array}
---

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/IN-ponds")

# Load packages
require("corrplot")
require("cowplot")
load(file = "~/GitHub/IN-ponds/data/MicrobialCommunity/INPond_Initial.RData")

env <- read.table("~/GitHub/IN-ponds/data/Environmental/20130801_PondDataMod.csv",
                  sep = ",", header = TRUE)
env <- env[complete.cases(env), ]
env[which(env$Sample_ID == "HNF133"), ]["SpC"] <- 55

#env$canopy <- log(env$canopy)
env$chla <- log(env$chla)
#env$SpC <- log(env$SpC)
#env$TDS <- log(env$TDS)
#env$Salinity <- log(env$Salinity + 0.01)
#env$DON <- log(env$DON)
#env$DOC <- log(env$DOC)
#env$DO <- log(env$DO)
#env$TP <- log(env$TP)
#env$Temp <- log(env$Temp)
#env$ORP <- log(env$ORP)
#env$Color <- log(env$Color)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}
par(mfrow=c(4, 3), mar = c(5,5,3,1))

xvar <- env$TP
xl <- "TP"

corr <- cor.test(xvar, env$canopy, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$canopy, ylab="canopy", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$DO, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$DO, ylab="DO", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$ORP, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$ORP, ylab="ORP", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$DON, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$DON, ylab="DON", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$chla, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$chla, ylab="chl-a", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$Temp, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$Temp, ylab="Temp", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$pH, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$pH, ylab="pH", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$DOC, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$DOC, ylab="DOC", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$Color, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$Color, ylab="Color", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$Salinity, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$Salinity, ylab="Salinity", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$TDS, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$TDS, ylab="TDS", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))

corr <- cor.test(xvar, env$Depth, method="pearson")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(xvar, env$Depth, ylab="Depth", xlab=xl,
  col = "black", cex=1, cex.lab=1.2, cex.axis = 1,
  main=paste("r =", c, ", p =", p))
```


