---
title: "Univariate relationships in IN Ponds data"
geometry: margin=2.54cm
output: pdf_document
header-includes: \usepackage{array}
---


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/DistDecay")

# Load packages
require("simba")
require("fossil")
require("corrplot")
require("cowplot")
load(file = "~/GitHub/DistDecay/data/MicrobialCommunity/INPond_Initial.RData")

# Functions to calculate Anne Chao's richness metric
S.obs <- function(x = ""){length(x[x > 0])}
S.chao1 <- function(x = ""){S.obs(x) + (sum(x == 1)^2) / (2 * sum(x == 2))}

# Select DNA Data: Use the `grep()` Command and Rename with `gsub()`
# The active portion, based on cDNA
act.com <- Pond97[grep("*-cDNA", rownames(Pond97)), ]
rownames(act.com) <- gsub("\\-cDNA", "", rownames(act.com))

# The community without respect to active or not, 16S rRNA gene sequences
all.com <- Pond97[grep("*-DNA", rownames(Pond97)), ]
rownames(all.com) <- gsub("\\-DNA", "", rownames(all.com))

# Remove Zero-Occurrence Taxa
act.com <- act.com[ , colSums(act.com) > 0]
all.com <- all.com[ , colSums(all.com) > 0]
all.com <- all.com[rownames(all.com)  %in% row.names(act.com),]
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(2, 2), mar = c(5,5,3,1), oma =c(0,0,6,0))

N.act <- log10(rowSums(act.com))
N.all <- log10(rowSums(all.com))

S.act <- log10(rowSums(act.com > 0))
S.all <- log10(rowSums(all.com > 0))

S.chao.act <- log10(apply(act.com, 1, S.chao1))
S.chao.all <- log10(apply(all.com, 1, S.chao1))

plot(N.all, N.act, xlab="N.all", ylab="N.active", cex.lab=1.25)
abline(lm(N.act ~ N.all))
  
plot(S.all, S.act, xlab="S.all", ylab="S.active", cex.lab=1.25)
abline(lm(S.act ~ S.all))

plot(N.all, S.all, xlab="N.all", ylab="S.all", cex.lab=1.25)
abline(lm(S.all ~ N.all))

plot(N.act, S.act, xlab="N.active", ylab="S.active", cex.lab=1.25)
abline(lm(S.act ~ N.act))

title(main="Results from molecular data", line=1, outer=T, cex.main=2)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Load Environmental and Geographical data
env <- read.table("~/GitHub/DistDecay/data/Environmental/20130801_PondDataMod.csv", 
                  sep = ",", header = TRUE)
env <- env[complete.cases(env),]
env[which(env$Sample_ID == "HNF133"), ]["SpC"] <- 55
env$chla <- log10(env$chla)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Load Flow Cytometry Data
flo <- read.table("~/GitHub/DistDecay/data/FlowCytometry/INPonds_flowdat.csv", 
                  sep = ",", header = TRUE)
flo <- flo[complete.cases(flo),]

levels(flo$pond) <- sub("_", "", levels(flo$pond))
levels(flo$pond) <- sub("BCSP", "BC", levels(flo$pond))
flo <- within(flo, rm("sample"))

N.tot <- log10(flo$N.totdens)
N.liv <- log10(flo$N.livedens)
N.ded <- log10(flo$N.deaddens)
rna <- log10(flo$meanRNA)
dna <- log10(flo$meanDNA)
rna.dna  <- log10(flo$mean.RNADNA)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(2, 2), mar = c(5,5,3,1), oma =c(0,0,6,0))

plot(N.liv, rna, xlab="Density of live cells, log10", ylab="RNA", cex.lab=1.25)
abline(lm(rna ~ N.liv))
  
plot(N.liv, dna, xlab="Density of live cells, log10", ylab="DNA", cex.lab=1.25)
abline(lm(dna ~ N.liv))

plot(N.liv, rna.dna, xlab="Density of live cells, log10", ylab="RNA:DNA", cex.lab=1.25)
abline(lm(rna.dna ~ N.liv))

plot(N.liv, N.ded, xlab="Density of live cells, log10", 
     ylab="Density of dead cells, log10", cex.lab=1.25)
abline(lm(N.ded ~ N.liv))
abline(a=0, b=1, col="red")

title(main="Results from flow cytometry data", line=1, outer=T, cex.main=2)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(2, 2), mar = c(5,5,3,1), oma =c(0,0,6,0))

plot(N.tot, rna, xlab="Total density of cells, log10", ylab="RNA", cex.lab=1.25)
abline(lm(rna ~ N.tot))
  
plot(N.tot, dna, xlab="Total density of cells, log10", ylab="DNA", cex.lab=1.25)
abline(lm(dna ~ N.tot))

plot(N.tot, rna.dna, xlab="Total density of cells, log10", ylab="RNA:DNA", cex.lab=1.25)
abline(lm(rna.dna ~ N.tot))

plot(N.tot, N.ded, xlab="Total density of cells, log10", 
     ylab="Density of dead cells, log10", cex.lab=1.25)
abline(lm(N.ded ~ N.tot))

title(main="Results from flow cytometry data", line=1, outer=T, cex.main=2)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Remove sites not shared between Community and Flow data
act.com <- act.com[rownames(act.com)  %in% flo$pond, ]
all.com <- all.com[rownames(all.com)  %in% row.names(act.com),]
flo <- flo[flo$pond %in% row.names(act.com), ]
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
N.act <- log10(rowSums(act.com))
N.all <- log10(rowSums(all.com))

S.act <- log10(rowSums(act.com > 0))
S.all <- log10(rowSums(all.com > 0))

S.chao.act <- log10(apply(act.com, 1, S.chao1))
S.chao.all <- log10(apply(all.com, 1, S.chao1))

N.tot <- log10(flo$N.totdens)
N.liv <- log10(flo$N.livedens)
N.ded <- log10(flo$N.deaddens)
rna <- flo$meanRNA
dna <- flo$meanDNA
rna.dna  <- flo$mean.RNADNA
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(2, 2), mar = c(5,5,3,1), oma =c(0,0,6,0))

plot(N.liv, S.all, xlab="Density of live cells, log10", ylab="S(total)", cex.lab=1.25)
abline(lm(S.all ~ N.liv))
  
plot(N.liv, S.act, xlab="Density of live cells, log10", ylab="S(active)", cex.lab=1.25)
abline(lm(S.act ~ N.liv))

plot(N.liv, N.all, xlab="Density of live cells, log10", ylab="N(total)", cex.lab=1.25)
abline(lm(N.all ~ N.liv))

plot(N.liv, N.act, xlab="Density of live cells, log10", ylab="N(active)", cex.lab=1.25)
abline(lm(N.act ~ N.liv))

title(main="Molecular data Vs. Flow cytometry data", line=1, outer=T, cex.main=2)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 3), mar = c(5,5,3,1), oma =c(0,0,6,0))

plot(rna.dna, S.all, xlab="RNA:DNA", ylab="S(total)", cex.lab=1.25)
abline(lm(S.all ~ rna.dna))
  
plot(rna.dna, S.act, xlab="RNA:DNA", ylab="S(active)", cex.lab=1.25)
abline(lm(S.act ~ rna.dna))

plot(rna.dna, N.all, xlab="RNA:DNA", ylab="N(total)", cex.lab=1.25)
abline(lm(N.all ~ rna.dna))

plot(rna.dna, N.act, xlab="RNA:DNA", ylab="N(active)", cex.lab=1.25)
abline(lm(N.act ~ rna.dna))

plot(dna, S.all, xlab="DNA", ylab="S(total)", cex.lab=1.25)
abline(lm(S.all ~ dna))
  
plot(dna, S.act, xlab="DNA", ylab="S(active)", cex.lab=1.25)
abline(lm(S.act ~ dna))

plot(dna, N.all, xlab="DNA", ylab="N(total)", cex.lab=1.25)
abline(lm(N.all ~ dna))

plot(dna, N.act, xlab="DNA", ylab="N(active)", cex.lab=1.25)
abline(lm(N.act ~ dna))

title(main="Molecular data Vs. Flow cytometry data", line=1, outer=T, cex.main=2)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}

# First, remove sites not shared between the Environmental and Flow Cytometry data
env <- env[env$Sample_ID %in% flo$pond, ]
flo <- flo[flo$pond %in% env$Sample_ID, ]

env$TP <- log10(env$TP)
env$DOC <- log10(env$DOC)
env$DO <- log10(env$DO)

env$N.tot <- log10(flo$N.totdens)
env$N.ded <- log10(flo$N.deaddens)
env$N.liv <- log10(flo$N.livedens)
env$rna <- log10(flo$meanRNA)
env$dna <- log10(flo$meanDNA)
env$rna.dna  <- log10(flo$mean.RNADNA)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 3), mar = c(5,5,3,1), oma =c(0,0,6,0))
p <- 1

plot(env$TP, env$rna.dna, ylab="RNA:DNA", xlab="TP", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$TP))
  
plot(env$DOC, env$rna.dna, ylab="RNA:DNA", xlab="DOC", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$DOC))

plot(env$DON, env$rna.dna, ylab="RNA:DNA", xlab="DON", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$DON))

plot(env$chla, env$rna.dna, ylab="RNA:DNA", xlab="chla", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$chla))

plot(env$DO, env$rna.dna, ylab="RNA:DNA", xlab="DO", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$DO)) 
  
plot(env$canopy, env$rna.dna, ylab="RNA:DNA", xlab="canopy", cex.lab=1.25)
abline(lm(env$rna.dna ~ env$canopy)) 

title(main="Flow cytometry data Vs. Environmental data", line=1, outer=T, cex.main=2)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 3), mar = c(5,5,3,1), oma =c(0,0,6,0))
p <- 1

plot(env$TP, env$rna, ylab="RNA", xlab="TP", cex.lab=1.25)
abline(lm(env$rna ~ env$TP))
  
plot(env$DOC, env$rna, ylab="RNA", xlab="DOC", cex.lab=1.25)
abline(lm(env$rna ~ env$DOC))

plot(env$DON, env$rna, ylab="RNA", xlab="DON", cex.lab=1.25)
abline(lm(env$rna ~ env$DON))

plot(env$chla, env$rna, ylab="RNA", xlab="chla", cex.lab=1.25)
abline(lm(env$rna ~ env$chla))

plot(env$DO, env$rna, ylab="RNA", xlab="DO", cex.lab=1.25)
abline(lm(env$rna ~ env$DO))

plot(env$canopy, env$rna, ylab="RNA", xlab="canopy", cex.lab=1.25)
abline(lm(env$rna ~ env$canopy))

title(main="Flow cytometry data Vs. Environmental data", line=1, outer=T, cex.main=2)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 3), mar = c(5,5,3,1), oma =c(0,0,6,0))
p <- 1

plot(env$TP, env$N.liv, ylab="Live density", xlab="TP", cex.lab=1.25)
abline(lm(env$N.liv ~ env$TP))

plot(env$DOC, env$N.liv, ylab="Live density", xlab="DOC", cex.lab=1.25)
abline(lm(env$N.liv ~ env$DOC))

plot(env$DON, env$N.liv, ylab="Live density", xlab="DON", cex.lab=1.25)
abline(lm(env$N.liv ~ env$DON))

plot(env$chla, env$N.liv, ylab="Live density", xlab="chla", cex.lab=1.25)
abline(lm(env$N.liv ~ env$chla))

plot(env$DO, env$N.liv, ylab="Live density", xlab="DO", cex.lab=1.25)
abline(lm(env$N.liv ~ env$DO))
  
plot(env$canopy, env$N.liv, ylab="Live density", xlab="canopy", cex.lab=1.25)
abline(lm(env$N.liv ~ env$canopy))

title(main="Flow cytometry data Vs. Environmental data", line=1, outer=T, cex.main=2)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 3), mar = c(5,5,3,1), oma =c(0,0,6,0))
p <- 1

plot(env$TP, env$N.tot, ylab="Total density", xlab="TP", cex.lab=1.25)
abline(lm(env$N.tot ~ env$TP))
  
plot(env$DOC, env$N.tot, ylab="Total density", xlab="DOC", cex.lab=1.25)
abline(lm(env$N.tot ~ env$DOC))

plot(env$DON, env$N.tot, ylab="Total density", xlab="DON", cex.lab=1.25)
abline(lm(env$N.tot ~ env$DON))

plot(env$chla, env$N.tot, ylab="Total density", xlab="chla", cex.lab=1.25)
abline(lm(env$N.tot ~ env$chla))

plot(env$DO, env$N.tot, ylab="Total density", xlab="DO", cex.lab=1.25)
abline(lm(env$N.tot ~ env$DO))
  
plot(env$canopy, env$N.tot, ylab="Total density", xlab="canopy", cex.lab=1.25)
abline(lm(env$N.tot ~ env$canopy))

title(main="Flow cytometry data Vs. Environmental data", line=1, outer=T, cex.main=2)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=8}

plot.new()
par(mfrow=c(3, 2), mar = c(5,5,3,1), oma =c(0,0,6,0))
p <- 1

corr <- cor.test(env$TP, env$rna.dna, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$TP, env$rna.dna, ylab="RNA:DNA", xlab="TP", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$rna.dna ~ env$TP))

corr <- cor.test(env$TP, env$N.liv, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$TP, env$N.liv, ylab="Live density", xlab="TP", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$N.liv ~ env$TP))

corr <- cor.test(env$DO, env$rna.dna, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$DO, env$rna.dna, ylab="RNA:DNA", xlab="DO", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$rna.dna ~ env$DO))

corr <- cor.test(env$DO, env$N.liv, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$DO, env$N.liv, ylab="Live density", xlab="DO", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$N.liv ~ env$DO))

corr <- cor.test(env$DOC, env$rna.dna, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$DOC, env$rna.dna, ylab="RNA:DNA", xlab="DOC", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$rna.dna ~ env$DOC))

corr <- cor.test(env$DOC, env$N.liv, method="spearman")
p <- round(corr$p.value,3)
c <- round(corr$estimate,2)
plot(env$DOC, env$N.liv, ylab="Live density", xlab="DOC", cex.lab=1.25,
     cex=1, cex.axis = 1, main=paste("r =", c, ", p =", p))
abline(lm(env$N.liv ~ env$DOC))
```