---
title: "Univariate relationships in IN Ponds data"
geometry: margin=2.54cm
output: pdf_document
header-includes: \usepackage{array}
---

```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/DormancyDecay")

# Load packages
require("corrplot")
require("cowplot")
#load(file = "~/GitHub/IN-ponds/data/MicrobialCommunity/INPond_Initial.RData")
```


```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
env <- read.table("~/GitHub/DormancyDecay/data/Environmental/20130801_INPondDataMod.csv",
                  sep = ",", header = TRUE)

env <- env[complete.cases(env), ]
env[which(env$Sample_ID == "HNF133"), ]["SpC"] <- 55
env[which(env$Sample_ID == "YSF46"), ]["lat"] <- 39.1186

#env$DO <- log(env$DO)
#env$canopy <- log(env$canopy)
#env$Color <- log(env$Color)
#env$chla <- log(env$chla)
#env$SpC <- log(env$SpC)
#env$DON <- log(env$DON)
#env$DOC <- log(env$DOC)

env <- env[env$SpC > 2 , ]
```


```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}

canopy <- env$canopy
DO <- env$DO
TP <- env$TP
ORP <- env$ORP
pH <- env$pH
Temp <- env$Temp
DOC <- env$DOC
DON <- env$DON
SpC <- env$SpC
TDS <- env$TDS
Salinity <- env$Salinity
chla <- env$chla
Color <- env$Color
Depth <- env$Depth

xvar <- SpC

df <- data.frame(x=xvar, y=canopy)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.A <- (ggplot(df, aes(x=SpC, y=canopy)) +
  geom_point(size = 3, alpha = 0.4)) + 
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=DO)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.B <- (ggplot(df, aes(x=SpC, y=DO)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=ORP)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.C <- (ggplot(df, aes(x=SpC,y=ORP)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=pH)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.D <- (ggplot(df, aes(x=SpC, y=pH)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=DON)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.E <- (ggplot(df, aes(x=SpC, y=DON)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=TDS)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.F <- (ggplot(df, aes(x=SpC, y=TDS)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=Salinity)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.G <- (ggplot(df, aes(x=SpC, y=Salinity)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=Depth)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.H <- (ggplot(df, aes(x=SpC, y=Depth)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=TP)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.I <- (ggplot(df, aes(x=SpC, y=TP)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

plot_grid(plot.A, plot.B, plot.C, plot.D, plot.E, plot.F, plot.G, plot.H,
        plot.I, labels = c("A", "B", "C", "D", "E", "F", "G", "H", "I"))
```


```{r, results = 'hide', echo=TRUE, message = FALSE, warning = FALSE}
df <- data.frame(x=xvar, y=DOC)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.A <- (ggplot(df, aes(x=SpC, y=DOC)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("pearson's =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=Temp)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.B <- (ggplot(df, aes(x=SpC, y=Temp)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=Color)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.C <- (ggplot(df, aes(x=SpC, y=Color)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

df <- data.frame(x=xvar, y=chla)
corr <- cor.test(df$x, df$y, method="pearson")
p <- corr$p.value
c <- corr$estimate
plot.D <- (ggplot(df, aes(x=SpC, y=chla)) +
  geom_point(size = 3, alpha = 0.4)) +
  labs(title = paste("r =", round(c, 2), ", p =", round(p,4)))

plot_grid(plot.A, plot.B, plot.C, plot.D, labels = c("A", "B", "C", "D"))
```
