---
title: "Supplemental Figures: Compositional similarity vs. Geographic distance"
geometry: margin=2.54cm
date: "November 7, 2015"
output: pdf_document
header-includes: \usepackage{array}
---

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/dist-decay/distdecay")

# Load packages
require("fossil")
require("simba")
load(file = "~/GitHub/IN-ponds/data/MicrobialCommunity/INPond_Initial.RData")
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Load Environmental and Geographical Data
env <- read.table("~/GitHub/IN-ponds/data/Environmental/20130801_PondDataMod.csv", sep = ",", header = TRUE)
env <- env[complete.cases(env),]

# Select DNA Data: Use the `grep()` Command and Rename with `gsub()`
# The active portion, based on cDNA
active.com <- Pond97[grep("*-cDNA", rownames(Pond97)), ]
rownames(active.com) <- gsub("\\-cDNA", "", rownames(active.com))

# The community without respect to active or not, 16S rRNA gene sequences
all.com <- Pond97[grep("*-DNA", rownames(Pond97)), ]
rownames(all.com) <- gsub("\\-DNA", "", rownames(all.com))

# Remove Sites Not in the Environmental Data Set
active.com <- active.com[rownames(active.com)  %in% env$Sample_ID, ]
all.com <- all.com[rownames(all.com)  %in% env$Sample_ID, ]

# Remove sites not shared between matrices
df <- as.data.frame(active.com)
all.com <- all.com[rownames(all.com)  %in% row.names(df),]
env <- env[env$Sample_ID %in% row.names(df),]
```


```{r}
# Geographic Distances (Kilometers) Among Ponds
long.lat <- as.matrix(cbind(env$long, env$lat))
geo.dist <- earth.dist(long.lat, dist = TRUE)
geo.dist <- log(geo.dist)
geo.dist[which(!is.finite(geo.dist))] = NA
```

```{r}
# Conduct PCA and get axes
# Define Environmental Matrix
# Pond environmental variables
env.dat <- as.matrix(subset(env, select = Elevation:TP))
env.chem <- env.dat

# Standardize and center
env.chem <- scale(env.chem, center = TRUE, scale = TRUE)

# Conduct PCA 
pca <- princomp(env.chem)
subscores <- as.data.frame(pca$scores[,1])
allscores <- as.data.frame(pca$scores)
all.pca.dist <- log(vegdist(allscores, "euclidean"))
sub.pca.dist <- log(vegdist(subscores, "euclidean"))
```


```{r}
file <- paste("~/GitHub/IN-ponds/figs/Env_vs_Geo.png", sep="")
png(filename=file)

plot.new()
par(mfrow=c(1, 2), mar = c(4, 5, 1, 1) + 0.1, pty="s")

pca_vs_geo <- lm(all.pca.dist ~ geo.dist)
summary(pca_vs_geo, correlation = TRUE)
slope <- round(coefficients(pca_vs_geo)[2], 3)
p <- round(summary(pca_vs_geo)$coefficients[8], 3)

smoothScatter(geo.dist, all.pca.dist, ylab="log(diff in PCA score)", xlab="log(Distance), km",
  col = NULL, cex=1, cex.lab=1.5, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))
title(paste("All PCA axes\nslope = ", slope, ", p =",p), line = 1)
abline(pca_vs_geo, col = "black", lwd=3)


pca_vs_geo <- lm(sub.pca.dist ~ geo.dist)
summary(pca_vs_geo, correlation = TRUE)
slope <- round(coefficients(pca_vs_geo)[2], 3)
p <- round(summary(pca_vs_geo)$coefficients[8], 3)

smoothScatter(geo.dist, sub.pca.dist, ylab="log(diff in PCA score)", xlab="log(Distance), km",
  col = NULL, cex=1, cex.lab=1.5, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))
title(paste("PCA axis 1\nslope = ", slope, ", p =",p), line = 1)
abline(pca_vs_geo, col = "black", lwd=3)

dev.off()
```
