---
title: "Supplemental Figures: Compositional similarity vs. Geographic distance"
geometry: margin=2.54cm
date: "November 7, 2015"
output: pdf_document
header-includes: \usepackage{array}
---

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/DistDecay/analyses/DistanceDecay")

# Load packages
require("simba")
require("fossil")
require("data.table")
load(file = "~/GitHub/DistDecay/data/MicrobialCommunity/INPond_Initial.RData")

# Load Environmental and Geographical Data
env <- read.table("~/GitHub/DistDecay/data/Environmental/20130801_PondDataMod.csv", sep = ",", header = TRUE)
env <- env[complete.cases(env),]
env[which(env$Sample_ID == "HNF133"), ]["SpC"] <- 55
env$chla <- log(env$chla)
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Select DNA Data: Use the `grep()` Command and Rename with `gsub()`
# The active portion, based on cDNA
act.com <- Pond97[grep("*-cDNA", rownames(Pond97)), ]
rownames(act.com) <- gsub("\\-cDNA", "", rownames(act.com))

# The community without respect to active or not, 16S rRNA gene sequences
all.com <- Pond97[grep("*-DNA", rownames(Pond97)), ]
rownames(all.com) <- gsub("\\-DNA", "", rownames(all.com))

# Remove Sites Not in the Environmental Data Set
act.com <- act.com[rownames(act.com)  %in% env$Sample_ID, ]
all.com <- all.com[rownames(all.com)  %in% env$Sample_ID, ]

# Remove sites not shared between matrices
all.com <- all.com[rownames(all.com)  %in% row.names(act.com),]
env <- env[env$Sample_ID %in% row.names(act.com),]

# Remove Zero-Occurrence Taxa
act.com <- act.com[,colSums(act.com) > 0]
all.com <- all.com[,colSums(all.com) > 0]
```



```{r}
# Define Environmental Matrix
env.dat <- as.matrix(subset(env, select = c("canopy", "DO", "ORP", "pH", "Temp", "DOC", "DON", "TDS", "Color", "chla", "TP", "Depth", "Salinity")))
env.dat2 <- scale(env.dat)

# Conduct PCA
pca <- princomp(env.dat2)
scores <- as.data.frame(pca$scores)

# Use relative abundance
act.com2 <- sweep(act.com, 1, rowSums(act.com), '/')
all.com2 <- sweep(all.com, 1, rowSums(all.com), '/')
```



```{r}
x.1 <- c()
x.2 <- c()
x.3 <- c()
x.4 <- c()
x.5 <- c()
x.6 <- c()
x.7 <- c()
x.8 <- c()
x.9 <- c()

y.act <- c()
y.all <- c()

for (c in c(1:10000)){
  
  otu <- sample(1:100, 1)
  site <- sample(1:49, 2, replace=FALSE)
  
  x1 <- env$Temp[site[1]]
  x2 <- env$Temp[site[2]]
  
  x3 <- env$chla[site[1]]
  x4 <- env$chla[site[2]]
  
  x5 <- env$canopy[site[1]]
  x6 <- env$canopy[site[2]]
  
  x7 <- env$TP[site[1]]
  x8 <- env$TP[site[2]]
  
  x9 <- env$ORP[site[1]]
  x10 <- env$ORP[site[2]]
  
  x11 <- env$ORP[site[1]]
  x12 <- env$ORP[site[2]]
  
  x13 <- env$DOC[site[1]]
  x14 <- env$DOC[site[2]]
  
  x15 <- env$DON[site[1]]
  x16 <- env$DON[site[2]]
  
  x17 <- env$DO[site[1]]
  x18 <- env$DO[site[2]]
  
  y1.act <- act.com2[site[1], otu]
  y2.act <- act.com2[site[2], otu]
  
  y1.all <- all.com2[site[1], otu]
  y2.all <- all.com2[site[2], otu]
  
  if (y1.act == 0 || y2.act == 0){ next}
  if (y1.all == 0 || y2.all == 0){ next}
  
  pdiff.x <- abs(x1 - x2)
  x.1 <- c(x.1, pdiff.x)
  
  pdiff.x <- abs(x3 - x4)
  x.2 <- c(x.2, pdiff.x)
  
  pdiff.x <- abs(x5 - x6)
  x.3 <- c(x.3, pdiff.x)
  
  pdiff.x <- abs(x7 - x8)
  x.4 <- c(x.4, pdiff.x)
  
  pdiff.x <- abs(x9 - x10)
  x.5 <- c(x.5, pdiff.x)
  
  pdiff.x <- abs(x11 - x12)
  x.6 <- c(x.6, pdiff.x)
  
  pdiff.x <- abs(x13 - x14)
  x.7 <- c(x.7, pdiff.x)
  
  pdiff.x <- abs(x15 - x16)
  x.8 <- c(x.8, pdiff.x)
  
  pdiff.x <- abs(x17 - x18)
  x.9 <- c(x.9, pdiff.x)
  
  pdiff.y <- abs(y1.act - y2.act) + 0.01
  y.act <- c(y.act, pdiff.y)
  
  pdiff.y <- abs(y1.all - y2.all) + 0.01
  y.all <- c(y.all, pdiff.y)
  
}

x.1 <- log10(x.1)
x.2 <- log10(x.2)
x.3 <- log10(x.3)
x.4 <- log10(x.4)
x.5 <- log10(x.5)
x.6 <- log10(x.6)
x.7 <- log10(x.7)
x.8 <- log10(x.8)
x.9 <- log10(x.9)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}

dat <- data.frame('x.1' = x.1, 'x.2' = x.2,
                  'x.3' = x.3, 'x.4' = x.4,
                  'x.5' = x.5, 'x.6' = x.6,
                  'x.7' = x.7, 'x.8' = x.8,
                  'x.9' = x.9, 'y' = log10(y.act))

dat[mapply(is.infinite, dat)] <- NA
dat <- dat[complete.cases(dat),]

par(mfrow=c(3, 3), mgp=c(3.1,1,0), mar = c(4,6,2,1), oma =c(3,3,0,0))

plot(dat$x.1, dat$y, ylab='', xlab='', main="Temperature", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)


plot(dat$x.2, dat$y, ylab='', xlab='', main="Chlorophyll-a", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.3, dat$y, ylab='', xlab='', main="Canopy", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.4, dat$y, ylab='', xlab='', main="Total Phosphorus", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.5, dat$y, ylab='', xlab='', main="pH", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.6, dat$y, ylab='', xlab='', main="Redox potential", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.7, dat$y, ylab='', xlab='', main="DOC", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.8, dat$y, ylab='', xlab='', main="DON", 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)

plot(dat$x.9, dat$y, ylab='', xlab='', main='DO', 
  cex.main = 1.5, col = 'azure4', cex=1, cex.lab=1, cex.axis = 1)


mtext("Difference in relative abundance, log10", 
      line=0, side=2, outer=TRUE, srt=90, cex=1.5)
mtext("Difference in environmental variable, log10", 
      line=1, side=1, outer=TRUE, cex=1.5)
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}

dat <- data.frame('x.1' = x.1, 'x.2' = x.2,
                  'x.3' = x.3, 'x.4' = x.4,
                  'x.5' = x.5, 'x.6' = x.6,
                  'x.7' = x.7, 'x.8' = x.8,
                  'x.9' = x.9, 'y' = log10(y.act))

dat[mapply(is.infinite, dat)] <- NA
dat <- dat[complete.cases(dat),]

par(mfrow=c(3, 3), mgp=c(3.1,1,0), mar = c(4,6,2,1), oma =c(3,3,0,0))

smoothScatter(dat$x.1, dat$y, 
  ylab='', xlab='', main="Temperature", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.2, dat$y, 
  ylab='', xlab='', main="Chlorophyll-a", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.3, dat$y, 
  ylab='', xlab='', main="Canopy", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.4, dat$y, 
  ylab='', xlab='', main="Total Phosphorus", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.5, dat$y, 
  ylab='', xlab='', main="pH", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.6, dat$y, 
  ylab='', xlab='', main="Redox potential", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.7, dat$y, 
  ylab='', xlab='', main="DOC", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.8, dat$y, 
  ylab='', xlab='', main="DON", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.9, dat$y, 
  ylab='', xlab='', main='DO', cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))


mtext("Difference in relative abundance, log10", 
      line=0, side=2, outer=TRUE, srt=90, cex=1.5)
mtext("Difference in environmental variable, log10", 
      line=1, side=1, outer=TRUE, cex=1.5)
```




```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}

dat <- data.frame('x.1' = x.1, 'x.2' = x.2,
                  'x.3' = x.3, 'x.4' = x.4,
                  'x.5' = x.5, 'x.6' = x.6,
                  'x.7' = x.7, 'x.8' = x.8,
                  'x.9' = x.9, 'y' = log10(y.all))

dat[mapply(is.infinite, dat)] <- NA
dat <- dat[complete.cases(dat),]

par(mfrow=c(3, 3), mgp=c(3.1,1,0), mar = c(4,6,2,1), oma =c(3,3,0,0))

smoothScatter(dat$x.1, dat$y, 
  ylab='', xlab='', main="Temperature", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.2, dat$y, 
  ylab='', xlab='', main="Chlorophyll-a", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.3, dat$y, 
  ylab='', xlab='', main="Canopy", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.4, dat$y, 
  ylab='', xlab='', main="Total Phosphorus", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.5, dat$y, 
  ylab='', xlab='', main="pH", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.6, dat$y, 
  ylab='', xlab='', main="Redox potential", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.7, dat$y, 
  ylab='', xlab='', main="DOC", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.8, dat$y, 
  ylab='', xlab='', main="DON", cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))

smoothScatter(dat$x.9, dat$y, 
  ylab='', xlab='', main='DO', cex.main = 1.5,
  col = NULL, cex=1, cex.lab=1, cex.axis = 1,
  colramp = colorRampPalette(c("white", "white", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000")))


mtext("Difference in relative abundance, log10", 
      line=0, side=2, outer=TRUE, srt=90, cex=1.5)
mtext("Difference in environmental variable, log10", 
      line=1, side=1, outer=TRUE, cex=1.5)
```